include $(global-env)
include $(path-script)/env/local.mk

include $(path-script)/image/image.mk
include $(path-script)/tool.mk
include $(path-script)/util.mk

.PHONY: start-image, end-image do-image
start-image:
	$(q)$(sudo) $(loop-setup) $(loop) $(path-img) -o $(offset-kernel)
	$(q)$(sudo) $(mount) $(loop) $(path-mount)

end-image:
	-$(q)$(sudo) $(umount) $(path-mount)
	-$(q)$(sudo) $(loop-setup) -d $(loop)

do-image:
	$(q)$(sudo) $(copy) $(target) $(path-mount)/$(path)