export ROOTDIR MODE BUILDDIR BINDIR OBJECTSDIR

#编译
.PHONY: build
build:
	cd tayboot ; make build

#清理
.PHONY: clean
clean:
	cd tayboot ; make clean

#写入镜像
.PHONY: image
image:
	cd tayboot ; make image