OBJECTSDIR := $(OBJECTSDIR)/drivers/
BINDIR := $(BINDIR)/drivers/
DRIVERSDIR := $(ROOTDIR)/drivers
export OBJECTSDIR DRIVERSDIR

#编译
.PHONY: build
build:
	echo "done!"

#清理
.PHONY: clean
clean:
	echo "done!"

.PHONY: image
image:
	echo "done!"